In this notebook, you will:
- learn a few signal processing functions in SigPy
- learn how to change computing device from CPU to GPU

https://sigpy.readthedocs.io/en/latest/core.html

In [1]:
%matplotlib notebook
import numpy as np
import sigpy as sp

# Centered FFT

In [2]:
x = np.array([1, 1, 1, 1], np.float)
y = sp.fft(x, center=True)

print('x = \n{}\n'.format(x))
print('y = \n{}\n'.format(y))

x = 
[1. 1. 1. 1.]

y = 
[0.+0.j 0.+0.j 2.+0.j 0.+0.j]



# NUFFT

In [9]:
x = np.array([1, 1, 1, 1], np.float)
coord = np.array([[-2], [-1], [0], [1]])
y = sp.nufft(x, coord)

print('x = \n{}\n'.format(x))
print('y = \n{}\n'.format(y))

x = 
[1. 1. 1. 1.]

y = 
[-1.19305942e-03-2.77555756e-17j  6.84182704e-04-4.49735772e-03j
  2.00461478e+00+0.00000000e+00j  6.84182704e-04+4.49735772e-03j]



# Convolution

In [4]:
x = np.array([1, 1, 0, 0], np.float)
h = np.array([1, 1], np.float)
y = sp.convolve(x, h)

print('x = \n{}\n'.format(x))
print('h = \n{}\n'.format(h))
print('y = \n{}\n'.format(y))

x = 
[1. 1. 0. 0.]

h = 
[1. 1.]

y = 
[ 1.00000000e+00  2.00000000e+00  1.00000000e+00 -5.55111512e-17
  1.11022302e-16]



In [5]:
x = np.array([1, 1, 0, 0], np.float)
h = np.array([[1, 1], [1, -1]], np.float)
y = sp.convolve(x, h, output_multi_channel=True)

print('x = \n{}\n'.format(x))
print('h = \n{}\n'.format(h))
print('y = \n{}\n'.format(y))

x = 
[1. 1. 0. 0.]

h = 
[[ 1.  1.]
 [ 1. -1.]]

y = 
[[ 1.00000000e+00  2.00000000e+00  1.00000000e+00 -5.55111512e-17
   1.11022302e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.00000000e+00  5.55111512e-17
  -5.55111512e-17]]



# Using GPU

In [6]:
import cupy as cp

ModuleNotFoundError: No module named 'cupy'

In [ ]:
x = cp.array([1, 1, 1, 1], np.float)
y = sp.fft(x, center=True)

print('x = \n{}\n'.format(x))
print('y = \n{}\n'.format(y))

In [7]:
device_id = 1
with sp.Device(device_id):
    x = cp.array([1, 1, 1, 1], np.float)
    y = sp.fft(x, center=True)
    
    print('x = \n{}\n'.format(x))
    print('y = \n{}\n'.format(y))

ValueError: cupy not installed, but set device 1.

In [ ]:
device = sp.get_device(x)

print('device is {}', device)

In [ ]:
device = sp.Device(0)
xp = device.xp
print('xp is {}'.format(xp))

![device](https://sigpy.readthedocs.io/en/latest/_images/device.pdf)